# Generated by Django 5.0.3 on 2024-05-27 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('historyNum', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=45)),
                ('arrival', models.CharField(max_length=45)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('userRelationNum', models.AutoField(primary_key=True, serialize=False)),
                ('helper_id', models.CharField(max_length=45)),
                ('recipient_id', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('userStateNum', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=45)),
                ('state', models.CharField(choices=[('Offline', '오프라인'), ('Walking', '도보'), ('Navigation', '네비게이션')], max_length=45)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=45)),
                ('option', models.CharField(choices=[('Protector', '보호자'), ('Protected', '피보호자')], max_length=45)),
                ('phoneNum', models.CharField(max_length=45)),
                ('apns_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
