# Generated by Django 5.0.3 on 2024-05-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='latitude',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='history',
            name='longitude',
            field=models.CharField(default='', max_length=45),
        ),
    ]
