# Generated by Django 5.0.3 on 2024-03-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='modify_date',
        ),
    ]
