# Generated by Django 5.0.3 on 2024-04-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camapp', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
