# Generated by Django 5.0.3 on 2024-04-06 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camapp', '0006_alter_post_options_post_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
    ]
