# Generated by Django 5.0.3 on 2024-04-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camapp', '0011_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
